<a href="https://colab.research.google.com/github/JARIN-TIAS/Deep_Learning-assignment/blob/main/Data_Preprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduce the Data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Summer 2022/CSE 511 (MSc)/Week-2/data.csv', na_values=['#NAME?'])

In [ ]:
df.head(10)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53.0,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,NaN,0,0,40,United-States,<=50K
4,28.0,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37.0,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49.0,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52.0,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31.0,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42.0,Private,159449.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

In [ ]:
df['income'].value_counts()

income
<=50K    3779
>50K     1221
Name: count, dtype: int64

In [ ]:
df['income'] = [0 if x == '<=50K' else 1 for x in df['income']]

In [ ]:
df['income'].value_counts()

0    3779
1    1221
Name: income, dtype: int64

In [ ]:
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53.0,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,NaN,0,0,40,United-States,0
4,28.0,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43.0,Private,222971.0,5th-6th,3.0,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Mexico,0
4996,31.0,Private,259425.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,1
4997,47.0,Self-emp-inc,212120.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,1
4998,NaN,Private,245880.0,HS-grad,9.0,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,60,United-States,0
4999,58.0,Local-gov,54947.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,55,United-States,0

In [ ]:
X = df.drop('income', 1)
y = df.income

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.

In [ ]:
X

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53.0,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,NaN,0,0,40,United-States
4,28.0,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43.0,Private,222971.0,5th-6th,3.0,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Mexico
4996,31.0,Private,259425.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
4997,47.0,Self-emp-inc,212120.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
4998,NaN,Private,245880.0,HS-grad,9.0,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,60,United-States
4999,58.0,Local-gov,54947.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,55,United-States

In [ ]:
y

0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
        ...
4995    <=50K
4996     >50K
4997     >50K
4998    <=50K
4999    <=50K
Name: income, Length: 5000, dtype: object

## Basic data cleaning

In [ ]:
X['education_num'].head(10)

0    13.0
1    13.0
2     9.0
3     7.0
4    13.0
5    14.0
6     5.0
7     9.0
8    14.0
9    13.0
Name: education_num, dtype: float64

In [ ]:
X['education'].head(10)

0    Bachelors
1    Bachelors
2      HS-grad
3         11th
4    Bachelors
5      Masters
6          9th
7      HS-grad
8      Masters
9    Bachelors
Name: education, dtype: object

In [ ]:
pd.get_dummies(X['education']).head(5)

,10th,11th,12th,1st-4th,5th-6th,7th-8th,9th,?,Assoc-acdm,Assoc-voc,Bachelors,Doctorate,HS-grad,Masters,Preschool,Prof-school,Some-college
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [ ]:
for col_name in X.columns:
    if X[col_name].dtypes == 'object':
        unique_cat = len(X[col_name].unique())
        print(f"Feature '{col_name}' has {unique_cat} unique categories")

Feature 'workclass' has 8 unique categories
Feature 'education' has 17 unique categories
Feature 'marital_status' has 7 unique categories
Feature 'occupation' has 15 unique categories
Feature 'relationship' has 6 unique categories
Feature 'race' has 6 unique categories
Feature 'sex' has 3 unique categories
Feature 'native_country' has 40 unique categories

In [ ]:
X['native_country'].value_counts().sort_values(ascending=False)

United-States                 4465
Mexico                         104
?                               97
Canada                          28
Philippines                     22
Germany                         22
El-Salvador                     16
Puerto-Rico                     16
England                         16
China                           15
Jamaica                         15
Cuba                            14
Dominican-Republic              13
Italy                           12
India                           12
Iran                            11
Vietnam                         10
Taiwan                          10
Guatemala                       10
Japan                            9
South                            9
Poland                           9
Portugal                         7
Greece                           6
Haiti                            6
Columbia                         5
Nicaragua                        5
Ecuador                          4
Cambodia                         4
Ireland                          4
Trinadad&Tobago                  4
France                           3
Peru                             3
Outlying-US(Guam-USVI-etc)       3
Honduras                         3
Yugoslavia                       2
Thailand                         2
Laos                             2
Scotland                         1
Hong                             1
Name: native_country, dtype: int64

In [ ]:
X['native_country'] = ['United-States ' if x == 'United-States' else 'Other' for x in X['native_country']]

In [ ]:
X['native_country'].value_counts().sort_values(ascending=False)

United-States     4465
Other              535
Name: native_country, dtype: int64

In [ ]:
todummy_list = ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'native_country']

In [ ]:
# Function to dummy all the categorical variables used for modeling
def dummy_df(df, todummy_list):
    for x in todummy_list:
        dummies = pd.get_dummies(df[x], prefix=x, dummy_na=False)
        df = df.drop(x, 1)
        df = pd.concat([df, dummies], axis=1)
    return df

In [ ]:
X = dummy_df(X, todummy_list)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """

In [ ]:
X

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,workclass_?,workclass_Federal-gov,workclass_Local-gov,workclass_Private,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39.0,77516.0,13.0,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,50.0,83311.0,13.0,0,0,13,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,38.0,215646.0,9.0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,53.0,234721.0,7.0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4,28.0,338409.0,13.0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43.0,222971.0,3.0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4996,31.0,259425.0,9.0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4997,47.0,212120.0,9.0,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4998,NaN,245880.0,9.0,0,0,60,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4999,58.0,54947.0,10.0,0,0,55,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

###  Handling missing data

In [ ]:
X.isnull().sum().sort_values(ascending=False).head()

race             264
fnlwgt           107
education_num     57
age               48
sex               47
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')

imputer.fit(X)
X = pd.DataFrame(data=imputer.transform(X) , columns=X.columns)

In [ ]:
X.isnull().sum().sort_values(ascending=False).head()

age                           0
occupation_Farming-fishing    0
occupation_Protective-serv    0
occupation_Prof-specialty     0
occupation_Priv-house-serv    0
dtype: int64

In [ ]:
for i in X:
  print(i)

age
fnlwgt
education_num
capital_gain
capital_loss
hours_per_week
workclass_?
workclass_Federal-gov
workclass_Local-gov
workclass_Private
workclass_Self-emp-inc
workclass_Self-emp-not-inc
workclass_State-gov
workclass_Without-pay
education_10th
education_11th
education_12th
education_1st-4th
education_5th-6th
education_7th-8th
education_9th
education_?
education_Assoc-acdm
education_Assoc-voc
education_Bachelors
education_Doctorate
education_HS-grad
education_Masters
education_Preschool
education_Prof-school
education_Some-college
marital_status_Divorced
marital_status_Married-AF-spouse
marital_status_Married-civ-spouse
marital_status_Married-spouse-absent
marital_status_Never-married
marital_status_Separated
marital_status_Widowed
occupation_?
occupation_Adm-clerical
occupation_Armed-Forces
occupation_Craft-repair
occupation_Exec-managerial
occupation_Farming-fishing
occupation_Handlers-cleaners
occupation_Machine-op-inspct
occupation_Other-service
occupation_Priv-house-serv
occupation_Prof-specialty
occupation_Protective-serv
occupation_Sales
occupation_Tech-support
occupation_Transport-moving
relationship_Husband
relationship_Not-in-family
relationship_Other-relative
relationship_Own-child
relationship_Unmarried
relationship_Wife
race_Amer-Indian-Eskimo
race_Asian-Pac-Islander
race_Black
race_Other
race_White
sex_Female
sex_Male
native_country_Other
native_country_United-States
age_fnlwgt
age_education_num
age_capital_gain
age_capital_loss
age_hours_per_week
age_workclass_?
age_workclass_Federal-gov
age_workclass_Local-gov
age_workclass_Private
age_workclass_Self-emp-inc
age_workclass_Self-emp-not-inc
age_workclass_State-gov
age_workclass_Without-pay
age_education_10th
age_education_11th
age_education_12th
age_education_1st-4th
age_education_5th-6th
age_education_7th-8th
age_education_9th
age_education_?
age_education_Assoc-acdm
age_education_Assoc-voc
age_education_Bachelors
age_education_Doctorate
age_education_HS-grad
age_education_Masters
age_education_Preschool
age_education_Prof-school
age_education_Some-college
age_marital_status_Divorced
age_marital_status_Married-AF-spouse
age_marital_status_Married-civ-spouse
age_marital_status_Married-spouse-absent
age_marital_status_Never-married
age_marital_status_Separated
age_marital_status_Widowed
age_occupation_?
age_occupation_Adm-clerical
age_occupation_Armed-Forces
age_occupation_Craft-repair
age_occupation_Exec-managerial
age_occupation_Farming-fishing
age_occupation_Handlers-cleaners
age_occupation_Machine-op-inspct
age_occupation_Other-service
age_occupation_Priv-house-serv
age_occupation_Prof-specialty
age_occupation_Protective-serv
age_occupation_Sales
age_occupation_Tech-support
age_occupation_Transport-moving
age_relationship_Husband
age_relationship_Not-in-family
age_relationship_Other-relative
age_relationship_Own-child
age_relationship_Unmarried
age_relationship_Wife
age_race_Amer-Indian-Eskimo
age_race_Asian-Pac-Islander
age_race_Black
age_race_Other
age_race_White
age_sex_Female
age_sex_Male
age_native_country_Other
age_native_country_United-States
fnlwgt_education_num
fnlwgt_capital_gain
fnlwgt_capital_loss
fnlwgt_hours_per_week
fnlwgt_workclass_?
fnlwgt_workclass_Federal-gov
fnlwgt_workclass_Local-gov
fnlwgt_workclass_Private
fnlwgt_workclass_Self-emp-inc
fnlwgt_workclass_Self-emp-not-inc
fnlwgt_workclass_State-gov
fnlwgt_workclass_Without-pay
fnlwgt_education_10th
fnlwgt_education_11th
fnlwgt_education_12th
fnlwgt_education_1st-4th
fnlwgt_education_5th-6th
fnlwgt_education_7th-8th
fnlwgt_education_9th
fnlwgt_education_?
fnlwgt_education_Assoc-acdm
fnlwgt_education_Assoc-voc
fnlwgt_education_Bachelors
fnlwgt_education_Doctorate
fnlwgt_education_HS-grad
fnlwgt_education_Masters
fnlwgt_education_Preschool
fnlwgt_education_Prof-school
fnlwgt_education_Some-college
fnlwgt_marital_status_Divorced
fnlwgt_marital_status_Married-AF-spouse
fnlwgt_marital_status_Married-civ-spouse
fnlwgt_marital_status_Married-spouse-absent
fnlwgt_marital_status_Never-married
fnlwgt_marital_status_Separated
fnlwgt_marital_status_Widowed
fnlwgt_occupation_?
fnlwgt_occupation_Adm-clerical
fnlwgt_occupation_Armed-Forces
fnlwgt_occupation_Craft-repair
fnlwgt_occupation_Exec-managerial
fnlwgt_occupation_Farming-fishing
fnlwgt_occupation_Handlers-cleaners
fnlwgt_occupation_Machine-op-inspct
fnlwgt_occupation_Other-service
fnlwgt_occupation_Priv-house-serv
fnlwgt_occupation_Prof-specialty
fnlwgt_occupation_Protective-serv
fnlwgt_occupation_Sales
fnlwgt_occupation_Tech-support
fnlwgt_occupation_Transport-moving
fnlwgt_relationship_Husband
fnlwgt_relationship_Not-in-family
fnlwgt_relationship_Other-relative
fnlwgt_relationship_Own-child
fnlwgt_relationship_Unmarried
fnlwgt_relationship_Wife
fnlwgt_race_Amer-Indian-Eskimo
fnlwgt_race_Asian-Pac-Islander
fnlwgt_race_Black
fnlwgt_race_Other
fnlwgt_race_White
fnlwgt_sex_Female
fnlwgt_sex_Male
fnlwgt_native_country_Other
fnlwgt_native_country_United-States
education_num_capital_gain
education_num_capital_loss
education_num_hours_per_week
education_num_workclass_?
education_num_workclass_Federal-gov
education_num_workclass_Local-gov
education_num_workclass_Private
education_num_workclass_Self-emp-inc
education_num_workclass_Self-emp-not-inc
education_num_workclass_State-gov
education_num_workclass_Without-pay
education_num_education_10th
education_num_education_11th
education_num_education_12th
education_num_education_1st-4th
education_num_education_5th-6th
education_num_education_7th-8th
education_num_education_9th
education_num_education_?
education_num_education_Assoc-acdm
education_num_education_Assoc-voc
education_num_education_Bachelors
education_num_education_Doctorate
education_num_education_HS-grad
education_num_education_Masters
education_num_education_Preschool
education_num_education_Prof-school
education_num_education_Some-college
education_num_marital_status_Divorced
education_num_marital_status_Married-AF-spouse
education_num_marital_status_Married-civ-spouse
education_num_marital_status_Married-spouse-absent
education_num_marital_status_Never-married
education_num_marital_status_Separated
education_num_marital_status_Widowed
education_num_occupation_?
education_num_occupation_Adm-clerical
education_num_occupation_Armed-Forces
education_num_occupation_Craft-repair
education_num_occupation_Exec-managerial
education_num_occupation_Farming-fishing
education_num_occupation_Handlers-cleaners
education_num_occupation_Machine-op-inspct
education_num_occupation_Other-service
education_num_occupation_Priv-house-serv
education_num_occupation_Prof-specialty
education_num_occupation_Protective-serv
education_num_occupation_Sales
education_num_occupation_Tech-support
education_num_occupation_Transport-moving
education_num_relationship_Husband
education_num_relationship_Not-in-family
education_num_relationship_Other-relative
education_num_relationship_Own-child
education_num_relationship_Unmarried
education_num_relationship_Wife
education_num_race_Amer-Indian-Eskimo
education_num_race_Asian-Pac-Islander
education_num_race_Black
education_num_race_Other
education_num_race_White
education_num_sex_Female
education_num_sex_Male
education_num_native_country_Other
education_num_native_country_United-States
capital_gain_hours_per_week
capital_gain_workclass_?
capital_gain_workclass_Federal-gov
capital_gain_workclass_Local-gov
capital_gain_workclass_Private
capital_gain_workclass_Self-emp-inc
capital_gain_workclass_Self-emp-not-inc
capital_gain_workclass_State-gov
capital_gain_education_10th
capital_gain_education_11th
capital_gain_education_12th
capital_gain_education_5th-6th
capital_gain_education_7th-8th
capital_gain_education_9th
capital_gain_education_?
capital_gain_education_Assoc-acdm
capital_gain_education_Assoc-voc
capital_gain_education_Bachelors
capital_gain_education_Doctorate
capital_gain_education_HS-grad
capital_gain_education_Masters
capital_gain_education_Prof-school
capital_gain_education_Some-college
capital_gain_marital_status_Divorced
capital_gain_marital_status_Married-civ-spouse
capital_gain_marital_status_Married-spouse-absent
capital_gain_marital_status_Never-married
capital_gain_marital_status_Separated
capital_gain_marital_status_Widowed
capital_gain_occupation_?
capital_gain_occupation_Adm-clerical
capital_gain_occupation_Craft-repair
capital_gain_occupation_Exec-managerial
capital_gain_occupation_Farming-fishing
capital_gain_occupation_Handlers-cleaners
capital_gain_occupation_Machine-op-inspct
capital_gain_occupation_Other-service
capital_gain_occupation_Priv-house-serv
capital_gain_occupation_Prof-specialty
capital_gain_occupation_Protective-serv
capital_gain_occupation_Sales
capital_gain_occupation_Tech-support
capital_gain_occupation_Transport-moving
capital_gain_relationship_Husband
capital_gain_relationship_Not-in-family
capital_gain_relationship_Other-relative
capital_gain_relationship_Own-child
capital_gain_relationship_Unmarried
capital_gain_relationship_Wife
capital_gain_race_Amer-Indian-Eskimo
capital_gain_race_Asian-Pac-Islander
capital_gain_race_Black
capital_gain_race_White
capital_gain_sex_Female
capital_gain_sex_Male
capital_gain_native_country_Other
capital_gain_native_country_United-States
capital_loss_hours_per_week
capital_loss_workclass_?
capital_loss_workclass_Federal-gov
capital_loss_workclass_Local-gov
capital_loss_workclass_Private
capital_loss_workclass_Self-emp-inc
capital_loss_workclass_Self-emp-not-inc
capital_loss_workclass_State-gov
capital_loss_education_10th
capital_loss_education_11th
capital_loss_education_12th
capital_loss_education_5th-6th
capital_loss_education_7th-8th
capital_loss_education_9th
capital_loss_education_?
capital_loss_education_Assoc-acdm
capital_loss_education_Assoc-voc
capital_loss_education_Bachelors
capital_loss_education_Doctorate
capital_loss_education_HS-grad
capital_loss_education_Masters
capital_loss_education_Prof-school
capital_loss_education_Some-college
capital_loss_marital_status_Divorced
capital_loss_marital_status_Married-civ-spouse
capital_loss_marital_status_Married-spouse-absent
capital_loss_marital_status_Never-married
capital_loss_marital_status_Separated
capital_loss_marital_status_Widowed
capital_loss_occupation_?
capital_loss_occupation_Adm-clerical
capital_loss_occupation_Craft-repair
capital_loss_occupation_Exec-managerial
capital_loss_occupation_Farming-fishing
capital_loss_occupation_Handlers-cleaners
capital_loss_occupation_Machine-op-inspct
capital_loss_occupation_Other-service
capital_loss_occupation_Prof-specialty
capital_loss_occupation_Protective-serv
capital_loss_occupation_Sales
capital_loss_occupation_Tech-support
capital_loss_occupation_Transport-moving
capital_loss_relationship_Husband
capital_loss_relationship_Not-in-family
capital_loss_relationship_Other-relative
capital_loss_relationship_Own-child
capital_loss_relationship_Unmarried
capital_loss_relationship_Wife
capital_loss_race_Asian-Pac-Islander
capital_loss_race_Black
capital_loss_race_Other
capital_loss_race_White
capital_loss_sex_Female
capital_loss_sex_Male
capital_loss_native_country_Other
capital_loss_native_country_United-States
hours_per_week_workclass_?
hours_per_week_workclass_Federal-gov
hours_per_week_workclass_Local-gov
hours_per_week_workclass_Private
hours_per_week_workclass_Self-emp-inc
hours_per_week_workclass_Self-emp-not-inc
hours_per_week_workclass_State-gov
hours_per_week_workclass_Without-pay
hours_per_week_education_10th
hours_per_week_education_11th
hours_per_week_education_12th
hours_per_week_education_1st-4th
hours_per_week_education_5th-6th
hours_per_week_education_7th-8th
hours_per_week_education_9th
hours_per_week_education_?
hours_per_week_education_Assoc-acdm
hours_per_week_education_Assoc-voc
hours_per_week_education_Bachelors
hours_per_week_education_Doctorate
hours_per_week_education_HS-grad
hours_per_week_education_Masters
hours_per_week_education_Preschool
hours_per_week_education_Prof-school
hours_per_week_education_Some-college
hours_per_week_marital_status_Divorced
hours_per_week_marital_status_Married-AF-spouse
hours_per_week_marital_status_Married-civ-spouse
hours_per_week_marital_status_Married-spouse-absent
hours_per_week_marital_status_Never-married
hours_per_week_marital_status_Separated
hours_per_week_marital_status_Widowed
hours_per_week_occupation_?
hours_per_week_occupation_Adm-clerical
hours_per_week_occupation_Armed-Forces
hours_per_week_occupation_Craft-repair
hours_per_week_occupation_Exec-managerial
hours_per_week_occupation_Farming-fishing
hours_per_week_occupation_Handlers-cleaners
hours_per_week_occupation_Machine-op-inspct
hours_per_week_occupation_Other-service
hours_per_week_occupation_Priv-house-serv
hours_per_week_occupation_Prof-specialty
hours_per_week_occupation_Protective-serv
hours_per_week_occupation_Sales
hours_per_week_occupation_Tech-support
hours_per_week_occupation_Transport-moving
hours_per_week_relationship_Husband
hours_per_week_relationship_Not-in-family
hours_per_week_relationship_Other-relative
hours_per_week_relationship_Own-child
hours_per_week_relationship_Unmarried
hours_per_week_relationship_Wife
hours_per_week_race_Amer-Indian-Eskimo
hours_per_week_race_Asian-Pac-Islander
hours_per_week_race_Black
hours_per_week_race_Other
hours_per_week_race_White
hours_per_week_sex_Female
hours_per_week_sex_Male
hours_per_week_native_country_Other
hours_per_week_native_country_United-States
workclass_?_education_10th
workclass_?_education_11th
workclass_?_education_12th
workclass_?_education_1st-4th
workclass_?_education_5th-6th
workclass_?_education_7th-8th
workclass_?_education_9th
workclass_?_education_?
workclass_?_education_Assoc-acdm
workclass_?_education_Assoc-voc
workclass_?_education_Bachelors
workclass_?_education_Doctorate
workclass_?_education_HS-grad
workclass_?_education_Masters
workclass_?_education_Preschool
workclass_?_education_Some-college
workclass_?_marital_status_Divorced
workclass_?_marital_status_Married-AF-spouse
workclass_?_marital_status_Married-civ-spouse
workclass_?_marital_status_Married-spouse-absent
workclass_?_marital_status_Never-married
workclass_?_marital_status_Separated
workclass_?_marital_status_Widowed
workclass_?_occupation_?
workclass_?_relationship_Husband
workclass_?_relationship_Not-in-family
workclass_?_relationship_Other-relative
workclass_?_relationship_Own-child
workclass_?_relationship_Unmarried
workclass_?_relationship_Wife
workclass_?_race_Amer-Indian-Eskimo
workclass_?_race_Asian-Pac-Islander
workclass_?_race_Black
workclass_?_race_Other
workclass_?_race_White
workclass_?_sex_Female
workclass_?_sex_Male
workclass_?_native_country_Other
workclass_?_native_country_United-States
workclass_Federal-gov_education_11th
workclass_Federal-gov_education_12th
workclass_Federal-gov_education_7th-8th
workclass_Federal-gov_education_9th
workclass_Federal-gov_education_?
workclass_Federal-gov_education_Assoc-acdm
workclass_Federal-gov_education_Assoc-voc
workclass_Federal-gov_education_Bachelors
workclass_Federal-gov_education_Doctorate
workclass_Federal-gov_education_HS-grad
workclass_Federal-gov_education_Masters
workclass_Federal-gov_education_Prof-school
workclass_Federal-gov_education_Some-college
workclass_Federal-gov_marital_status_Divorced
workclass_Federal-gov_marital_status_Married-AF-spouse
workclass_Federal-gov_marital_status_Married-civ-spouse
workclass_Federal-gov_marital_status_Never-married
workclass_Federal-gov_marital_status_Separated
workclass_Federal-gov_marital_status_Widowed
workclass_Federal-gov_occupation_Adm-clerical
workclass_Federal-gov_occupation_Armed-Forces
workclass_Federal-gov_occupation_Craft-repair
workclass_Federal-gov_occupation_Exec-managerial
workclass_Federal-gov_occupation_Farming-fishing
workclass_Federal-gov_occupation_Handlers-cleaners
workclass_Federal-gov_occupation_Machine-op-inspct
workclass_Federal-gov_occupation_Other-service
workclass_Federal-gov_occupation_Prof-specialty
workclass_Federal-gov_occupation_Protective-serv
workclass_Federal-gov_occupation_Sales
workclass_Federal-gov_occupation_Tech-support
workclass_Federal-gov_occupation_Transport-moving
workclass_Federal-gov_relationship_Husband
workclass_Federal-gov_relationship_Not-in-family
workclass_Federal-gov_relationship_Other-relative
workclass_Federal-gov_relationship_Own-child
workclass_Federal-gov_relationship_Unmarried
workclass_Federal-gov_relationship_Wife
workclass_Federal-gov_race_Amer-Indian-Eskimo
workclass_Federal-gov_race_Asian-Pac-Islander
workclass_Federal-gov_race_Black
workclass_Federal-gov_race_White
workclass_Federal-gov_sex_Female
workclass_Federal-gov_sex_Male
workclass_Federal-gov_native_country_Other
workclass_Federal-gov_native_country_United-States
workclass_Local-gov_education_10th
workclass_Local-gov_education_11th
workclass_Local-gov_education_12th
workclass_Local-gov_education_7th-8th
workclass_Local-gov_education_9th
workclass_Local-gov_education_?
workclass_Local-gov_education_Assoc-acdm
workclass_Local-gov_education_Assoc-voc
workclass_Local-gov_education_Bachelors
workclass_Local-gov_education_Doctorate
workclass_Local-gov_education_HS-grad
workclass_Local-gov_education_Masters
workclass_Local-gov_education_Preschool
workclass_Local-gov_education_Prof-school
workclass_Local-gov_education_Some-college
workclass_Local-gov_marital_status_Divorced
workclass_Local-gov_marital_status_Married-civ-spouse
workclass_Local-gov_marital_status_Married-spouse-absent
workclass_Local-gov_marital_status_Never-married
workclass_Local-gov_marital_status_Separated
workclass_Local-gov_marital_status_Widowed
workclass_Local-gov_occupation_Adm-clerical
workclass_Local-gov_occupation_Craft-repair
workclass_Local-gov_occupation_Exec-managerial
workclass_Local-gov_occupation_Farming-fishing
workclass_Local-gov_occupation_Handlers-cleaners
workclass_Local-gov_occupation_Machine-op-inspct
workclass_Local-gov_occupation_Other-service
workclass_Local-gov_occupation_Prof-specialty
workclass_Local-gov_occupation_Protective-serv
workclass_Local-gov_occupation_Sales
workclass_Local-gov_occupation_Tech-support
workclass_Local-gov_occupation_Transport-moving
workclass_Local-gov_relationship_Husband
workclass_Local-gov_relationship_Not-in-family
workclass_Local-gov_relationship_Other-relative
workclass_Local-gov_relationship_Own-child
workclass_Local-gov_relationship_Unmarried
workclass_Local-gov_relationship_Wife
workclass_Local-gov_race_Amer-Indian-Eskimo
workclass_Local-gov_race_Asian-Pac-Islander
workclass_Local-gov_race_Black
workclass_Local-gov_race_White
workclass_Local-gov_sex_Female
workclass_Local-gov_sex_Male
workclass_Local-gov_native_country_Other
workclass_Local-gov_native_country_United-States
workclass_Private_education_10th
workclass_Private_education_11th
workclass_Private_education_12th
workclass_Private_education_1st-4th
workclass_Private_education_5th-6th
workclass_Private_education_7th-8th
workclass_Private_education_9th
workclass_Private_education_?
workclass_Private_education_Assoc-acdm
workclass_Private_education_Assoc-voc
workclass_Private_education_Bachelors
workclass_Private_education_Doctorate
workclass_Private_education_HS-grad
workclass_Private_education_Masters
workclass_Private_education_Preschool
workclass_Private_education_Prof-school
workclass_Private_education_Some-college
workclass_Private_marital_status_Divorced
workclass_Private_marital_status_Married-AF-spouse
workclass_Private_marital_status_Married-civ-spouse
workclass_Private_marital_status_Married-spouse-absent
workclass_Private_marital_status_Never-married
workclass_Private_marital_status_Separated
workclass_Private_marital_status_Widowed
workclass_Private_occupation_Adm-clerical
workclass_Private_occupation_Craft-repair
workclass_Private_occupation_Exec-managerial
workclass_Private_occupation_Farming-fishing
workclass_Private_occupation_Handlers-cleaners
workclass_Private_occupation_Machine-op-inspct
workclass_Private_occupation_Other-service
workclass_Private_occupation_Priv-house-serv
workclass_Private_occupation_Prof-specialty

### Dimensionality reduction using PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
X_pca = pd.DataFrame(pca.fit_transform(X))

In [ ]:
X_pca.head(5)

,0,1,2,3,4,5,6,7,8,9
0,-2.849607e+07,-1.778542e+07,-6.151562e+06,4.267630e+04,-6.416500e+04,50038.208696,-1746.473510,-23294.500107,98992.031235,-9719.998102
1,-1.970160e+08,-1.805201e+07,-6.763008e+06,2.240802e+06,-3.338928e+05,-20805.393947,-146910.204601,-37854.270476,38955.527303,-4423.679445
2,-1.970126e+08,-1.797630e+07,1.546966e+06,8.187336e+04,1.487265e+05,-17880.128372,93217.420722,113017.591146,3770.492127,-52114.476024
3,-1.970113e+08,-1.794623e+07,4.905983e+06,2.710393e+06,8.618040e+05,-14121.197310,-55097.952611,-46071.940149,-55352.106757,-155730.445631
4,-1.970106e+08,-1.793149e+07,6.335358e+06,-2.382846e+06,-1.512602e+06,45442.434681,-23203.304836,-463357.947327,-193040.059945,1777.881979

In [ ]:
print(df.shape)
print(X.shape)

(5000, 15)
(5000, 1737)